---
apiVersion: apps/v1
kind: Deployment
metadata: 
 name: nginx-deployment
 labels:
  apps: nginx
spec:
 replicas: 4
 selector:
  matchLabels:
   app: nginx
 template:
  metadata:
   labels:
    apps: nginx
  spec:
   containers:
    - name: nginx
      image: nginx
      ports:
       - containerPort: 80
         hostPort: 7700
...
