---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-rs
  labels:
   author: Rajesh
spec:
 replicas: 4
 selector:
  matchLabels:
   author: Rajesh
 template:
  metadata:
   name: httpd-pod
   labels:
    author: Rajesh
  spec:
   containers:
    - name: httpdserver
      image: httpd
      ports:
       - containerPort: 80
         hostPort: 7799
...
