---
apiVersion: v1
kind: ReplicationController
metadata:
 name: jenkins-rc
spec:
 replicas: 3
 template:
  metadata:
   name: jenkins-pod
   labels:
    author: Rajesh
  spec:
   containers:
    - name: jenkinsserver
      image: jenkins
      ports:
       - containerPort: 8080
         hostPort: 8090
...
