---
apiVersion: v1
kind: Pod
metadata:
 name: mysql-db
 labels:
  author: Rajesh
  type: database
spec:
 containers:
  - name: mysqldb
    image: mysql:5
    env:
     - name: MYSQL_ROOT_PASSWORD
       value: admin
...
