---
apiVersion: v1
kind: Pod
metadata:
 name: tomcat-pod
 labels:
  author: Rajesh
  type: webserver
spec:
 containers:
  - name: webserver
    image: tomcat:6
    ports:
     - containerPort: 8080
       hostPort: 6060
...
